-- Migration: Add content and length_minutes columns to scripts table and reload schema cache
-- Executed at: 2026-07-20T02:41:31Z
-- Generated by Could Code

ALTER TABLE scripts ADD COLUMN IF NOT EXISTS content JSONB;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS length_minutes INTEGER;

NOTIFY pgrst, 'reload schema';
