-- Migration: Check the current scripts table columns
-- Executed at: 2026-07-20T02:41:10Z
-- Generated by Could Code

SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'scripts';
