-- Migration: Supabase migration via Could Code
-- Executed at: 2026-07-20T02:46:05Z
-- Generated by Could Code

SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'scripts';
